kind: "BuildConfig"
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    name: mule-test-pipeline
  name: mule-test-pipeline
spec:
  source:
    git:
      uri: https://github.com/avenging/mule-test.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
