apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mule-hw
  namespace: mule
spec:
  host: mule-hello.osapps.192.168.121.44.nip.io
  to:
    kind: Service
    name: mule-helloworld
    weight: 100
  wildcardPolicy: None
